"""Numeric Operators Program!!"""
__author__ = "730228132"
x: str = input("Left-hand side : ")
y: str = input("Right-hand side : ")
t1_new = int(x) ** int(y)
ro = str(t1_new)
print("17 ** 8 " + "is " + ro)
t2_new = int(x) / int(y)
r1 = str(t2_new)
print("17 / 8 " + "is " + r1)
t3_new = int(x) // int(y)
r2 = str(t3_new)
print("17 // 8 " + "is " + r2)
t4_new = int(x) % int(y)
r3 = str(t4_new)
print("17 % 8 " + "is " + r3)